### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by juanezamudio** [lukedemi/gdax-notifier#3]
When I try to run the foreground of the app:

`docker run -it --rm --name gdax-notifier --env-file .env gdax-notifier`

I get this error:

`docker: Error response from daemon: Conflict. The container name "/gdax-notifier" is already in use by container "577e3a6e318d34e78b1d953375e1925cea23a2fdcd7a397cdd4db368ba202316". You have to remove (or rename) that container to be able to reuse that name.`

Are the arguments out of date for docker or is there something else going on?

**Comment by juanezamudio** [comment]
I figured out how to solve it by removing the:

`--name gdax-notifier` options

but now I get a bad connection error that was brought up in #2

**Comment by lukedemi** [comment]
🙏
